[2022-01-09 16:30:00,918] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-09T16:20:00+00:00 [queued]>
[2022-01-09 16:30:00,924] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-09T16:20:00+00:00 [queued]>
[2022-01-09 16:30:00,925] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-09 16:30:00,925] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-09 16:30:00,925] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-09 16:30:00,933] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): verificacao_log> on 2022-01-09 16:20:00+00:00
[2022-01-09 16:30:00,936] {standard_task_runner.py:52} INFO - Started process 126079 to run task
[2022-01-09 16:30:00,938] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'verificacao_log', 'scheduled__2022-01-09T16:20:00+00:00', '--job-id', '516', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpongo0suf', '--error-file', '/tmp/tmpse2sg4xb']
[2022-01-09 16:30:00,938] {standard_task_runner.py:77} INFO - Job 516: Subtask verificacao_log
[2022-01-09 16:30:00,965] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-09T16:20:00+00:00 [running]> on host fa901b562f08
[2022-01-09 16:30:00,998] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=verificacao_log
AIRFLOW_CTX_EXECUTION_DATE=2022-01-09T16:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-09T16:20:00+00:00
[2022-01-09 16:30:01,580] {logging_mixin.py:109} INFO - Data atual:  2022-01-09 16:30:01.580901
[2022-01-09 16:30:01,581] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/10 17:10:14
[2022-01-09 16:30:01,581] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  29 days, 23:19:47.580887
[2022-01-09 16:30:01,581] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/10 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2022-01-09 16:30:01,581] {logging_mixin.py:109} INFO - 
[2022-01-09 16:30:01,581] {my_dag.py:60} ERROR - tempo entre ultimo log e data atual maior que 10 minutos.
[2022-01-09 16:30:01,581] {python.py:152} INFO - Done. Returned value was: None
[2022-01-09 16:30:01,590] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=verificacao_log, execution_date=20220109T162000, start_date=20220109T163000, end_date=20220109T163001
[2022-01-09 16:30:01,632] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-09 16:30:01,654] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
