[2022-01-11 18:20:00,763] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.execute_dag scheduled__2022-01-11T18:10:00+00:00 [queued]>
[2022-01-11 18:20:00,771] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.execute_dag scheduled__2022-01-11T18:10:00+00:00 [queued]>
[2022-01-11 18:20:00,771] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 18:20:00,771] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-11 18:20:00,771] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 18:20:00,780] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): execute_dag> on 2022-01-11 18:10:00+00:00
[2022-01-11 18:20:00,784] {standard_task_runner.py:52} INFO - Started process 1534 to run task
[2022-01-11 18:20:00,786] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'execute_dag', 'scheduled__2022-01-11T18:10:00+00:00', '--job-id', '833', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpd2a5kvve', '--error-file', '/tmp/tmphmva7jm4']
[2022-01-11 18:20:00,786] {standard_task_runner.py:77} INFO - Job 833: Subtask execute_dag
[2022-01-11 18:20:00,813] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.execute_dag scheduled__2022-01-11T18:10:00+00:00 [running]> on host e382db28423e
[2022-01-11 18:20:00,846] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=iagosilva@mobitbrasil.com.br
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=execute_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-01-11T18:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-11T18:10:00+00:00
[2022-01-11 18:20:01,006] {logging_mixin.py:109} INFO - Data atual:  2022-01-11 18:20:01.006017
[2022-01-11 18:20:01,006] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/10 17:10:14
[2022-01-11 18:20:01,006] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  32 days, 1:09:47.005996
[2022-01-11 18:20:01,006] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/10 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2022-01-11 18:20:01,006] {logging_mixin.py:109} INFO - 
[2022-01-11 18:20:01,006] {my_dag.py:65} ERROR - tempo entre ultimo log e data atual maior que 10 minutos.
[2022-01-11 18:20:01,006] {python.py:152} INFO - Done. Returned value was: None
[2022-01-11 18:20:01,016] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=execute_dag, execution_date=20220111T181000, start_date=20220111T182000, end_date=20220111T182001
[2022-01-11 18:20:01,038] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-11 18:20:01,061] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
