[2022-01-11 00:50:01,227] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-11T00:40:00+00:00 [queued]>
[2022-01-11 00:50:01,234] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-11T00:40:00+00:00 [queued]>
[2022-01-11 00:50:01,234] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 00:50:01,234] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-11 00:50:01,234] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 00:50:01,242] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): verificacao_log> on 2022-01-11 00:40:00+00:00
[2022-01-11 00:50:01,245] {standard_task_runner.py:52} INFO - Started process 214267 to run task
[2022-01-11 00:50:01,248] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'verificacao_log', 'scheduled__2022-01-11T00:40:00+00:00', '--job-id', '709', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp3yv03b51', '--error-file', '/tmp/tmp0ajxffio']
[2022-01-11 00:50:01,248] {standard_task_runner.py:77} INFO - Job 709: Subtask verificacao_log
[2022-01-11 00:50:01,274] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-11T00:40:00+00:00 [running]> on host fa901b562f08
[2022-01-11 00:50:01,308] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=verificacao_log
AIRFLOW_CTX_EXECUTION_DATE=2022-01-11T00:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-11T00:40:00+00:00
[2022-01-11 00:50:01,481] {logging_mixin.py:109} INFO - Data atual:  2022-01-11 00:50:01.481468
[2022-01-11 00:50:01,481] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/10 17:10:14
[2022-01-11 00:50:01,481] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  31 days, 7:39:47.481456
[2022-01-11 00:50:01,481] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/10 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2022-01-11 00:50:01,481] {logging_mixin.py:109} INFO - 
[2022-01-11 00:50:01,481] {my_dag.py:60} ERROR - tempo entre ultimo log e data atual maior que 10 minutos.
[2022-01-11 00:50:01,482] {python.py:152} INFO - Done. Returned value was: None
[2022-01-11 00:50:01,492] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=verificacao_log, execution_date=20220111T004000, start_date=20220111T005001, end_date=20220111T005001
[2022-01-11 00:50:01,540] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-11 00:50:01,567] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
